### ISSUE TITLE
误差扩散算法

### ISSUE THREAD

**Issue by runner111** [sisong/demoForHssBlog#1]
请问如何能支持RGB666？我在您的算法上做了些修改，但是总是偏色。而且有些地方也看不太明白。比如 inline  long  getBestRGB16_555Color( const   long  wantColor)
    inline  long  getC8Color( const   long  rColor)
能详细讲一讲吗 @sisong

**Comment by sisong** [comment]
颜色处理时需要注意颜色bit数，类似于模拟浮点数的定点数计算；   
另外RGB666，意味着那保存这个值至少需要18bit颜色（或24bit、32bit都有可能），这里是否有误？

**Comment by runner111** [comment]
感谢您的回答 RGB666的排列方式是按字排列，这样会节省空间。也就是RRRRRRGG GGGGBBBB BBRRRR 是工业上包括某些手机屏幕的显示方式，我现在就是在找问题，请问那这两个函数内容需不需要更改？我改成移位6字了，这么改对吗？

**Comment by sisong** [comment]
用2分法定位bug
